nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin:
      - '%env(CORS_ALLOW_ORIGIN)%'
      - '^https://projet-m2-ldf-mars-avril-2\.onrender\.com$'
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/': null
